/*
Val Town API

Testing SearchAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package valgo

import (
	"context"
	"testing"

	openapiclient "github.com/404wolf/valgo"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_valgo_SearchAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SearchAPIService SearchVals", func(t *testing.T) {
		req := apiClient.SearchAPI.SearchVals(context.Background()).Query("xkcdcomicoftheday").Limit(2).Offset(0)
		resp, httpRes, err := req.Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
