/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BranchesList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BranchesList200Response{}

// BranchesList200Response A paginated result set
type BranchesList200Response struct {
	Data []Branch `json:"data"`
	Links PaginationLinks `json:"links"`
}

type _BranchesList200Response BranchesList200Response

// NewBranchesList200Response instantiates a new BranchesList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBranchesList200Response(data []Branch, links PaginationLinks) *BranchesList200Response {
	this := BranchesList200Response{}
	this.Data = data
	this.Links = links
	return &this
}

// NewBranchesList200ResponseWithDefaults instantiates a new BranchesList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBranchesList200ResponseWithDefaults() *BranchesList200Response {
	this := BranchesList200Response{}
	return &this
}

// GetData returns the Data field value
func (o *BranchesList200Response) GetData() []Branch {
	if o == nil {
		var ret []Branch
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BranchesList200Response) GetDataOk() ([]Branch, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BranchesList200Response) SetData(v []Branch) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *BranchesList200Response) GetLinks() PaginationLinks {
	if o == nil {
		var ret PaginationLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *BranchesList200Response) GetLinksOk() (*PaginationLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *BranchesList200Response) SetLinks(v PaginationLinks) {
	o.Links = v
}

func (o BranchesList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BranchesList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *BranchesList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBranchesList200Response := _BranchesList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBranchesList200Response)

	if err != nil {
		return err
	}

	*o = BranchesList200Response(varBranchesList200Response)

	return err
}

type NullableBranchesList200Response struct {
	value *BranchesList200Response
	isSet bool
}

func (v NullableBranchesList200Response) Get() *BranchesList200Response {
	return v.value
}

func (v *NullableBranchesList200Response) Set(val *BranchesList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBranchesList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBranchesList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBranchesList200Response(val *BranchesList200Response) *NullableBranchesList200Response {
	return &NullableBranchesList200Response{value: val, isSet: true}
}

func (v NullableBranchesList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBranchesList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


