/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailsSend500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailsSend500Response{}

// EmailsSend500Response struct for EmailsSend500Response
type EmailsSend500Response struct {
	Error string `json:"error"`
}

type _EmailsSend500Response EmailsSend500Response

// NewEmailsSend500Response instantiates a new EmailsSend500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailsSend500Response(error_ string) *EmailsSend500Response {
	this := EmailsSend500Response{}
	this.Error = error_
	return &this
}

// NewEmailsSend500ResponseWithDefaults instantiates a new EmailsSend500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailsSend500ResponseWithDefaults() *EmailsSend500Response {
	this := EmailsSend500Response{}
	return &this
}

// GetError returns the Error field value
func (o *EmailsSend500Response) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *EmailsSend500Response) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *EmailsSend500Response) SetError(v string) {
	o.Error = v
}

func (o EmailsSend500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailsSend500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *EmailsSend500Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailsSend500Response := _EmailsSend500Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailsSend500Response)

	if err != nil {
		return err
	}

	*o = EmailsSend500Response(varEmailsSend500Response)

	return err
}

type NullableEmailsSend500Response struct {
	value *EmailsSend500Response
	isSet bool
}

func (v NullableEmailsSend500Response) Get() *EmailsSend500Response {
	return v.value
}

func (v *NullableEmailsSend500Response) Set(val *EmailsSend500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailsSend500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailsSend500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailsSend500Response(val *EmailsSend500Response) *NullableEmailsSend500Response {
	return &NullableEmailsSend500Response{value: val, isSet: true}
}

func (v NullableEmailsSend500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailsSend500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


