/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RootProjectFilesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RootProjectFilesGet200Response{}

// RootProjectFilesGet200Response A paginated result set
type RootProjectFilesGet200Response struct {
	Data []FileRevisionMetadata `json:"data"`
	Links PaginationLinks `json:"links"`
}

type _RootProjectFilesGet200Response RootProjectFilesGet200Response

// NewRootProjectFilesGet200Response instantiates a new RootProjectFilesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRootProjectFilesGet200Response(data []FileRevisionMetadata, links PaginationLinks) *RootProjectFilesGet200Response {
	this := RootProjectFilesGet200Response{}
	this.Data = data
	this.Links = links
	return &this
}

// NewRootProjectFilesGet200ResponseWithDefaults instantiates a new RootProjectFilesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRootProjectFilesGet200ResponseWithDefaults() *RootProjectFilesGet200Response {
	this := RootProjectFilesGet200Response{}
	return &this
}

// GetData returns the Data field value
func (o *RootProjectFilesGet200Response) GetData() []FileRevisionMetadata {
	if o == nil {
		var ret []FileRevisionMetadata
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RootProjectFilesGet200Response) GetDataOk() ([]FileRevisionMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *RootProjectFilesGet200Response) SetData(v []FileRevisionMetadata) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *RootProjectFilesGet200Response) GetLinks() PaginationLinks {
	if o == nil {
		var ret PaginationLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *RootProjectFilesGet200Response) GetLinksOk() (*PaginationLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *RootProjectFilesGet200Response) SetLinks(v PaginationLinks) {
	o.Links = v
}

func (o RootProjectFilesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RootProjectFilesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *RootProjectFilesGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRootProjectFilesGet200Response := _RootProjectFilesGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRootProjectFilesGet200Response)

	if err != nil {
		return err
	}

	*o = RootProjectFilesGet200Response(varRootProjectFilesGet200Response)

	return err
}

type NullableRootProjectFilesGet200Response struct {
	value *RootProjectFilesGet200Response
	isSet bool
}

func (v NullableRootProjectFilesGet200Response) Get() *RootProjectFilesGet200Response {
	return v.value
}

func (v *NullableRootProjectFilesGet200Response) Set(val *RootProjectFilesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRootProjectFilesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRootProjectFilesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRootProjectFilesGet200Response(val *RootProjectFilesGet200Response) *NullableRootProjectFilesGet200Response {
	return &NullableRootProjectFilesGet200Response{value: val, isSet: true}
}

func (v NullableRootProjectFilesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRootProjectFilesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


