/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParameterizedQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParameterizedQuery{}

// ParameterizedQuery A parameterized SQL query. See https://docs.turso.tech/sdk/ts/reference#batch-transactions for reference
type ParameterizedQuery struct {
	// SQL statement, with ? placeholders for arguments
	Sql string `json:"sql"`
	Args StatementArg `json:"args"`
}

type _ParameterizedQuery ParameterizedQuery

// NewParameterizedQuery instantiates a new ParameterizedQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParameterizedQuery(sql string, args StatementArg) *ParameterizedQuery {
	this := ParameterizedQuery{}
	this.Sql = sql
	this.Args = args
	return &this
}

// NewParameterizedQueryWithDefaults instantiates a new ParameterizedQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParameterizedQueryWithDefaults() *ParameterizedQuery {
	this := ParameterizedQuery{}
	return &this
}

// GetSql returns the Sql field value
func (o *ParameterizedQuery) GetSql() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sql
}

// GetSqlOk returns a tuple with the Sql field value
// and a boolean to check if the value has been set.
func (o *ParameterizedQuery) GetSqlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sql, true
}

// SetSql sets field value
func (o *ParameterizedQuery) SetSql(v string) {
	o.Sql = v
}

// GetArgs returns the Args field value
func (o *ParameterizedQuery) GetArgs() StatementArg {
	if o == nil {
		var ret StatementArg
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *ParameterizedQuery) GetArgsOk() (*StatementArg, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *ParameterizedQuery) SetArgs(v StatementArg) {
	o.Args = v
}

func (o ParameterizedQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParameterizedQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sql"] = o.Sql
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *ParameterizedQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sql",
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParameterizedQuery := _ParameterizedQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParameterizedQuery)

	if err != nil {
		return err
	}

	*o = ParameterizedQuery(varParameterizedQuery)

	return err
}

type NullableParameterizedQuery struct {
	value *ParameterizedQuery
	isSet bool
}

func (v NullableParameterizedQuery) Get() *ParameterizedQuery {
	return v.value
}

func (v *NullableParameterizedQuery) Set(val *ParameterizedQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableParameterizedQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableParameterizedQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParameterizedQuery(val *ParameterizedQuery) *NullableParameterizedQuery {
	return &NullableParameterizedQuery{value: val, isSet: true}
}

func (v NullableParameterizedQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParameterizedQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


