/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MeProjects200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeProjects200Response{}

// MeProjects200Response A paginated result set
type MeProjects200Response struct {
	Data []Project `json:"data"`
	Links PaginationLinks `json:"links"`
}

type _MeProjects200Response MeProjects200Response

// NewMeProjects200Response instantiates a new MeProjects200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeProjects200Response(data []Project, links PaginationLinks) *MeProjects200Response {
	this := MeProjects200Response{}
	this.Data = data
	this.Links = links
	return &this
}

// NewMeProjects200ResponseWithDefaults instantiates a new MeProjects200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeProjects200ResponseWithDefaults() *MeProjects200Response {
	this := MeProjects200Response{}
	return &this
}

// GetData returns the Data field value
func (o *MeProjects200Response) GetData() []Project {
	if o == nil {
		var ret []Project
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MeProjects200Response) GetDataOk() ([]Project, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *MeProjects200Response) SetData(v []Project) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *MeProjects200Response) GetLinks() PaginationLinks {
	if o == nil {
		var ret PaginationLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *MeProjects200Response) GetLinksOk() (*PaginationLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *MeProjects200Response) SetLinks(v PaginationLinks) {
	o.Links = v
}

func (o MeProjects200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeProjects200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *MeProjects200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeProjects200Response := _MeProjects200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeProjects200Response)

	if err != nil {
		return err
	}

	*o = MeProjects200Response(varMeProjects200Response)

	return err
}

type NullableMeProjects200Response struct {
	value *MeProjects200Response
	isSet bool
}

func (v NullableMeProjects200Response) Get() *MeProjects200Response {
	return v.value
}

func (v *NullableMeProjects200Response) Set(val *MeProjects200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableMeProjects200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableMeProjects200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeProjects200Response(val *MeProjects200Response) *NullableMeProjects200Response {
	return &NullableMeProjects200Response{value: val, isSet: true}
}

func (v NullableMeProjects200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeProjects200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


