/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MeReferences200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeReferences200Response{}

// MeReferences200Response A paginated result set
type MeReferences200Response struct {
	Data []MeReferences200ResponseDataInner `json:"data"`
	Links PaginationLinks `json:"links"`
}

type _MeReferences200Response MeReferences200Response

// NewMeReferences200Response instantiates a new MeReferences200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeReferences200Response(data []MeReferences200ResponseDataInner, links PaginationLinks) *MeReferences200Response {
	this := MeReferences200Response{}
	this.Data = data
	this.Links = links
	return &this
}

// NewMeReferences200ResponseWithDefaults instantiates a new MeReferences200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeReferences200ResponseWithDefaults() *MeReferences200Response {
	this := MeReferences200Response{}
	return &this
}

// GetData returns the Data field value
func (o *MeReferences200Response) GetData() []MeReferences200ResponseDataInner {
	if o == nil {
		var ret []MeReferences200ResponseDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MeReferences200Response) GetDataOk() ([]MeReferences200ResponseDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *MeReferences200Response) SetData(v []MeReferences200ResponseDataInner) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *MeReferences200Response) GetLinks() PaginationLinks {
	if o == nil {
		var ret PaginationLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *MeReferences200Response) GetLinksOk() (*PaginationLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *MeReferences200Response) SetLinks(v PaginationLinks) {
	o.Links = v
}

func (o MeReferences200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeReferences200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *MeReferences200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeReferences200Response := _MeReferences200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeReferences200Response)

	if err != nil {
		return err
	}

	*o = MeReferences200Response(varMeReferences200Response)

	return err
}

type NullableMeReferences200Response struct {
	value *MeReferences200Response
	isSet bool
}

func (v NullableMeReferences200Response) Get() *MeReferences200Response {
	return v.value
}

func (v *NullableMeReferences200Response) Set(val *MeReferences200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableMeReferences200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableMeReferences200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeReferences200Response(val *MeReferences200Response) *NullableMeReferences200Response {
	return &NullableMeReferences200Response{value: val, isSet: true}
}

func (v NullableMeReferences200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeReferences200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


