/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"fmt"
)

// ReplyToList A reply-to list of email addresses
type ReplyToList struct {
	EmailNameAndAddress *EmailNameAndAddress
	ArrayOfEmailNameAndAddress *[]EmailNameAndAddress
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ReplyToList) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into EmailNameAndAddress
	err = json.Unmarshal(data, &dst.EmailNameAndAddress);
	if err == nil {
		jsonEmailNameAndAddress, _ := json.Marshal(dst.EmailNameAndAddress)
		if string(jsonEmailNameAndAddress) == "{}" { // empty struct
			dst.EmailNameAndAddress = nil
		} else {
			return nil // data stored in dst.EmailNameAndAddress, return on the first match
		}
	} else {
		dst.EmailNameAndAddress = nil
	}

	// try to unmarshal JSON data into ArrayOfEmailNameAndAddress
	err = json.Unmarshal(data, &dst.ArrayOfEmailNameAndAddress);
	if err == nil {
		jsonArrayOfEmailNameAndAddress, _ := json.Marshal(dst.ArrayOfEmailNameAndAddress)
		if string(jsonArrayOfEmailNameAndAddress) == "{}" { // empty struct
			dst.ArrayOfEmailNameAndAddress = nil
		} else {
			return nil // data stored in dst.ArrayOfEmailNameAndAddress, return on the first match
		}
	} else {
		dst.ArrayOfEmailNameAndAddress = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ReplyToList)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *ReplyToList) MarshalJSON() ([]byte, error) {
	if src.EmailNameAndAddress != nil {
		return json.Marshal(&src.EmailNameAndAddress)
	}

	if src.ArrayOfEmailNameAndAddress != nil {
		return json.Marshal(&src.ArrayOfEmailNameAndAddress)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableReplyToList struct {
	value *ReplyToList
	isSet bool
}

func (v NullableReplyToList) Get() *ReplyToList {
	return v.value
}

func (v *NullableReplyToList) Set(val *ReplyToList) {
	v.value = val
	v.isSet = true
}

func (v NullableReplyToList) IsSet() bool {
	return v.isSet
}

func (v *NullableReplyToList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplyToList(val *ReplyToList) *NullableReplyToList {
	return &NullableReplyToList{value: val, isSet: true}
}

func (v NullableReplyToList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplyToList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


