/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FileRevisionMetadataLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileRevisionMetadataLinks{}

// FileRevisionMetadataLinks struct for FileRevisionMetadataLinks
type FileRevisionMetadataLinks struct {
	// The URL of this resource on this API
	Self string `json:"self"`
	// The URL of this resource on Val Town
	Html string `json:"html"`
	// The URL of this resource's source code as a module
	Module string `json:"module"`
	// This resource's web endpoint, where it serves a website or API
	Endpoint *string `json:"endpoint,omitempty"`
}

type _FileRevisionMetadataLinks FileRevisionMetadataLinks

// NewFileRevisionMetadataLinks instantiates a new FileRevisionMetadataLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileRevisionMetadataLinks(self string, html string, module string) *FileRevisionMetadataLinks {
	this := FileRevisionMetadataLinks{}
	this.Self = self
	this.Html = html
	this.Module = module
	return &this
}

// NewFileRevisionMetadataLinksWithDefaults instantiates a new FileRevisionMetadataLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileRevisionMetadataLinksWithDefaults() *FileRevisionMetadataLinks {
	this := FileRevisionMetadataLinks{}
	return &this
}

// GetSelf returns the Self field value
func (o *FileRevisionMetadataLinks) GetSelf() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *FileRevisionMetadataLinks) GetSelfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *FileRevisionMetadataLinks) SetSelf(v string) {
	o.Self = v
}

// GetHtml returns the Html field value
func (o *FileRevisionMetadataLinks) GetHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Html
}

// GetHtmlOk returns a tuple with the Html field value
// and a boolean to check if the value has been set.
func (o *FileRevisionMetadataLinks) GetHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Html, true
}

// SetHtml sets field value
func (o *FileRevisionMetadataLinks) SetHtml(v string) {
	o.Html = v
}

// GetModule returns the Module field value
func (o *FileRevisionMetadataLinks) GetModule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Module
}

// GetModuleOk returns a tuple with the Module field value
// and a boolean to check if the value has been set.
func (o *FileRevisionMetadataLinks) GetModuleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Module, true
}

// SetModule sets field value
func (o *FileRevisionMetadataLinks) SetModule(v string) {
	o.Module = v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *FileRevisionMetadataLinks) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileRevisionMetadataLinks) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *FileRevisionMetadataLinks) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *FileRevisionMetadataLinks) SetEndpoint(v string) {
	o.Endpoint = &v
}

func (o FileRevisionMetadataLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileRevisionMetadataLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["self"] = o.Self
	toSerialize["html"] = o.Html
	toSerialize["module"] = o.Module
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	return toSerialize, nil
}

func (o *FileRevisionMetadataLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"self",
		"html",
		"module",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileRevisionMetadataLinks := _FileRevisionMetadataLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFileRevisionMetadataLinks)

	if err != nil {
		return err
	}

	*o = FileRevisionMetadataLinks(varFileRevisionMetadataLinks)

	return err
}

type NullableFileRevisionMetadataLinks struct {
	value *FileRevisionMetadataLinks
	isSet bool
}

func (v NullableFileRevisionMetadataLinks) Get() *FileRevisionMetadataLinks {
	return v.value
}

func (v *NullableFileRevisionMetadataLinks) Set(val *FileRevisionMetadataLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableFileRevisionMetadataLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableFileRevisionMetadataLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileRevisionMetadataLinks(val *FileRevisionMetadataLinks) *NullableFileRevisionMetadataLinks {
	return &NullableFileRevisionMetadataLinks{value: val, isSet: true}
}

func (v NullableFileRevisionMetadataLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileRevisionMetadataLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


