/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValsCancel200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValsCancel200Response{}

// ValsCancel200Response The evaluation_id was successfully searched for and the evaluation was either already done or now has been cancelled
type ValsCancel200Response struct {
	// True if the evaluation was found and cancelled
	Found bool `json:"found"`
}

type _ValsCancel200Response ValsCancel200Response

// NewValsCancel200Response instantiates a new ValsCancel200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValsCancel200Response(found bool) *ValsCancel200Response {
	this := ValsCancel200Response{}
	this.Found = found
	return &this
}

// NewValsCancel200ResponseWithDefaults instantiates a new ValsCancel200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValsCancel200ResponseWithDefaults() *ValsCancel200Response {
	this := ValsCancel200Response{}
	return &this
}

// GetFound returns the Found field value
func (o *ValsCancel200Response) GetFound() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Found
}

// GetFoundOk returns a tuple with the Found field value
// and a boolean to check if the value has been set.
func (o *ValsCancel200Response) GetFoundOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Found, true
}

// SetFound sets field value
func (o *ValsCancel200Response) SetFound(v bool) {
	o.Found = v
}

func (o ValsCancel200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValsCancel200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["found"] = o.Found
	return toSerialize, nil
}

func (o *ValsCancel200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"found",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValsCancel200Response := _ValsCancel200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValsCancel200Response)

	if err != nil {
		return err
	}

	*o = ValsCancel200Response(varValsCancel200Response)

	return err
}

type NullableValsCancel200Response struct {
	value *ValsCancel200Response
	isSet bool
}

func (v NullableValsCancel200Response) Get() *ValsCancel200Response {
	return v.value
}

func (v *NullableValsCancel200Response) Set(val *ValsCancel200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableValsCancel200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableValsCancel200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValsCancel200Response(val *ValsCancel200Response) *NullableValsCancel200Response {
	return &NullableValsCancel200Response{value: val, isSet: true}
}

func (v NullableValsCancel200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValsCancel200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


