/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"fmt"
)

// StatementArg List of arguments to be used in the given statement
type StatementArg struct {
	ArrayOfAny *[]interface{}
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *StatementArg) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ArrayOfAny
	err = json.Unmarshal(data, &dst.ArrayOfAny);
	if err == nil {
		jsonArrayOfAny, _ := json.Marshal(dst.ArrayOfAny)
		if string(jsonArrayOfAny) == "{}" { // empty struct
			dst.ArrayOfAny = nil
		} else {
			return nil // data stored in dst.ArrayOfAny, return on the first match
		}
	} else {
		dst.ArrayOfAny = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(StatementArg)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *StatementArg) MarshalJSON() ([]byte, error) {
	if src.ArrayOfAny != nil {
		return json.Marshal(&src.ArrayOfAny)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableStatementArg struct {
	value *StatementArg
	isSet bool
}

func (v NullableStatementArg) Get() *StatementArg {
	return v.value
}

func (v *NullableStatementArg) Set(val *StatementArg) {
	v.value = val
	v.isSet = true
}

func (v NullableStatementArg) IsSet() bool {
	return v.isSet
}

func (v *NullableStatementArg) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatementArg(val *StatementArg) *NullableStatementArg {
	return &NullableStatementArg{value: val, isSet: true}
}

func (v NullableStatementArg) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatementArg) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


