/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the User type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &User{}

// User User object
type User struct {
	// The ID of this user
	Id string `json:"id"`
	// The user’s biography, if they have provided one
	Bio NullableString `json:"bio"`
	// The user’s handle that they chose for themselves. Does not include the @ symbol
	Username NullableString `json:"username"`
	// URL that points to the user’s profile image, if one exists
	ProfileImageUrl NullableString `json:"profileImageUrl"`
	// URL of this user’s profile on Val Town’s website
	Url string `json:"url"`
	Links MeGet200ResponseLinks `json:"links"`
}

type _User User

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser(id string, bio NullableString, username NullableString, profileImageUrl NullableString, url string, links MeGet200ResponseLinks) *User {
	this := User{}
	this.Id = id
	this.Bio = bio
	this.Username = username
	this.ProfileImageUrl = profileImageUrl
	this.Url = url
	this.Links = links
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetId returns the Id field value
func (o *User) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *User) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *User) SetId(v string) {
	o.Id = v
}

// GetBio returns the Bio field value
// If the value is explicit nil, the zero value for string will be returned
func (o *User) GetBio() string {
	if o == nil || o.Bio.Get() == nil {
		var ret string
		return ret
	}

	return *o.Bio.Get()
}

// GetBioOk returns a tuple with the Bio field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetBioOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bio.Get(), o.Bio.IsSet()
}

// SetBio sets field value
func (o *User) SetBio(v string) {
	o.Bio.Set(&v)
}

// GetUsername returns the Username field value
// If the value is explicit nil, the zero value for string will be returned
func (o *User) GetUsername() string {
	if o == nil || o.Username.Get() == nil {
		var ret string
		return ret
	}

	return *o.Username.Get()
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Username.Get(), o.Username.IsSet()
}

// SetUsername sets field value
func (o *User) SetUsername(v string) {
	o.Username.Set(&v)
}

// GetProfileImageUrl returns the ProfileImageUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *User) GetProfileImageUrl() string {
	if o == nil || o.ProfileImageUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.ProfileImageUrl.Get()
}

// GetProfileImageUrlOk returns a tuple with the ProfileImageUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetProfileImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProfileImageUrl.Get(), o.ProfileImageUrl.IsSet()
}

// SetProfileImageUrl sets field value
func (o *User) SetProfileImageUrl(v string) {
	o.ProfileImageUrl.Set(&v)
}

// GetUrl returns the Url field value
func (o *User) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *User) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *User) SetUrl(v string) {
	o.Url = v
}

// GetLinks returns the Links field value
func (o *User) GetLinks() MeGet200ResponseLinks {
	if o == nil {
		var ret MeGet200ResponseLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *User) GetLinksOk() (*MeGet200ResponseLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *User) SetLinks(v MeGet200ResponseLinks) {
	o.Links = v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o User) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["bio"] = o.Bio.Get()
	toSerialize["username"] = o.Username.Get()
	toSerialize["profileImageUrl"] = o.ProfileImageUrl.Get()
	toSerialize["url"] = o.Url
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *User) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"bio",
		"username",
		"profileImageUrl",
		"url",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUser := _User{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUser)

	if err != nil {
		return err
	}

	*o = User(varUser)

	return err
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


