/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AliasVal200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AliasVal200ResponseLinks{}

// AliasVal200ResponseLinks struct for AliasVal200ResponseLinks
type AliasVal200ResponseLinks struct {
	// The URL of this val on this API
	Self string `json:"self"`
	// The endpoint to retrieve this val’s versions
	Versions string `json:"versions"`
	// The URL of this Val’s source code as a module
	Module string `json:"module"`
	// This val’s web endpoint, where it serves a website or API
	Endpoint *string `json:"endpoint,omitempty"`
}

type _AliasVal200ResponseLinks AliasVal200ResponseLinks

// NewAliasVal200ResponseLinks instantiates a new AliasVal200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAliasVal200ResponseLinks(self string, versions string, module string) *AliasVal200ResponseLinks {
	this := AliasVal200ResponseLinks{}
	this.Self = self
	this.Versions = versions
	this.Module = module
	return &this
}

// NewAliasVal200ResponseLinksWithDefaults instantiates a new AliasVal200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAliasVal200ResponseLinksWithDefaults() *AliasVal200ResponseLinks {
	this := AliasVal200ResponseLinks{}
	return &this
}

// GetSelf returns the Self field value
func (o *AliasVal200ResponseLinks) GetSelf() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *AliasVal200ResponseLinks) GetSelfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *AliasVal200ResponseLinks) SetSelf(v string) {
	o.Self = v
}

// GetVersions returns the Versions field value
func (o *AliasVal200ResponseLinks) GetVersions() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value
// and a boolean to check if the value has been set.
func (o *AliasVal200ResponseLinks) GetVersionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Versions, true
}

// SetVersions sets field value
func (o *AliasVal200ResponseLinks) SetVersions(v string) {
	o.Versions = v
}

// GetModule returns the Module field value
func (o *AliasVal200ResponseLinks) GetModule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Module
}

// GetModuleOk returns a tuple with the Module field value
// and a boolean to check if the value has been set.
func (o *AliasVal200ResponseLinks) GetModuleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Module, true
}

// SetModule sets field value
func (o *AliasVal200ResponseLinks) SetModule(v string) {
	o.Module = v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *AliasVal200ResponseLinks) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AliasVal200ResponseLinks) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *AliasVal200ResponseLinks) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *AliasVal200ResponseLinks) SetEndpoint(v string) {
	o.Endpoint = &v
}

func (o AliasVal200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AliasVal200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["self"] = o.Self
	toSerialize["versions"] = o.Versions
	toSerialize["module"] = o.Module
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	return toSerialize, nil
}

func (o *AliasVal200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"self",
		"versions",
		"module",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAliasVal200ResponseLinks := _AliasVal200ResponseLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAliasVal200ResponseLinks)

	if err != nil {
		return err
	}

	*o = AliasVal200ResponseLinks(varAliasVal200ResponseLinks)

	return err
}

type NullableAliasVal200ResponseLinks struct {
	value *AliasVal200ResponseLinks
	isSet bool
}

func (v NullableAliasVal200ResponseLinks) Get() *AliasVal200ResponseLinks {
	return v.value
}

func (v *NullableAliasVal200ResponseLinks) Set(val *AliasVal200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableAliasVal200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableAliasVal200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAliasVal200ResponseLinks(val *AliasVal200ResponseLinks) *NullableAliasVal200ResponseLinks {
	return &NullableAliasVal200ResponseLinks{value: val, isSet: true}
}

func (v NullableAliasVal200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAliasVal200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


