/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailsSend200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailsSend200Response{}

// EmailsSend200Response Successfully sent email
type EmailsSend200Response struct {
	Message string `json:"message"`
}

type _EmailsSend200Response EmailsSend200Response

// NewEmailsSend200Response instantiates a new EmailsSend200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailsSend200Response(message string) *EmailsSend200Response {
	this := EmailsSend200Response{}
	this.Message = message
	return &this
}

// NewEmailsSend200ResponseWithDefaults instantiates a new EmailsSend200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailsSend200ResponseWithDefaults() *EmailsSend200Response {
	this := EmailsSend200Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *EmailsSend200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *EmailsSend200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *EmailsSend200Response) SetMessage(v string) {
	o.Message = v
}

func (o EmailsSend200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailsSend200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *EmailsSend200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailsSend200Response := _EmailsSend200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailsSend200Response)

	if err != nil {
		return err
	}

	*o = EmailsSend200Response(varEmailsSend200Response)

	return err
}

type NullableEmailsSend200Response struct {
	value *EmailsSend200Response
	isSet bool
}

func (v NullableEmailsSend200Response) Get() *EmailsSend200Response {
	return v.value
}

func (v *NullableEmailsSend200Response) Set(val *EmailsSend200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailsSend200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailsSend200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailsSend200Response(val *EmailsSend200Response) *NullableEmailsSend200Response {
	return &NullableEmailsSend200Response{value: val, isSet: true}
}

func (v NullableEmailsSend200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailsSend200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


