/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MeComments200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeComments200Response{}

// MeComments200Response A paginated result set
type MeComments200Response struct {
	Data []MeComments200ResponseDataInner `json:"data"`
	Links PaginationLinks `json:"links"`
}

type _MeComments200Response MeComments200Response

// NewMeComments200Response instantiates a new MeComments200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeComments200Response(data []MeComments200ResponseDataInner, links PaginationLinks) *MeComments200Response {
	this := MeComments200Response{}
	this.Data = data
	this.Links = links
	return &this
}

// NewMeComments200ResponseWithDefaults instantiates a new MeComments200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeComments200ResponseWithDefaults() *MeComments200Response {
	this := MeComments200Response{}
	return &this
}

// GetData returns the Data field value
func (o *MeComments200Response) GetData() []MeComments200ResponseDataInner {
	if o == nil {
		var ret []MeComments200ResponseDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MeComments200Response) GetDataOk() ([]MeComments200ResponseDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *MeComments200Response) SetData(v []MeComments200ResponseDataInner) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *MeComments200Response) GetLinks() PaginationLinks {
	if o == nil {
		var ret PaginationLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *MeComments200Response) GetLinksOk() (*PaginationLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *MeComments200Response) SetLinks(v PaginationLinks) {
	o.Links = v
}

func (o MeComments200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeComments200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *MeComments200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeComments200Response := _MeComments200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeComments200Response)

	if err != nil {
		return err
	}

	*o = MeComments200Response(varMeComments200Response)

	return err
}

type NullableMeComments200Response struct {
	value *MeComments200Response
	isSet bool
}

func (v NullableMeComments200Response) Get() *MeComments200Response {
	return v.value
}

func (v *NullableMeComments200Response) Set(val *MeComments200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableMeComments200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableMeComments200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeComments200Response(val *MeComments200Response) *NullableMeComments200Response {
	return &NullableMeComments200Response{value: val, isSet: true}
}

func (v NullableMeComments200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeComments200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


