/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValsPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValsPutRequest{}

// ValsPutRequest Create a new val, or version of a val, with new code
type ValsPutRequest struct {
	// Val source code as TypeScript
	Code string `json:"code"`
	// This val’s name
	Name string `json:"name"`
}

type _ValsPutRequest ValsPutRequest

// NewValsPutRequest instantiates a new ValsPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValsPutRequest(code string, name string) *ValsPutRequest {
	this := ValsPutRequest{}
	this.Code = code
	this.Name = name
	return &this
}

// NewValsPutRequestWithDefaults instantiates a new ValsPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValsPutRequestWithDefaults() *ValsPutRequest {
	this := ValsPutRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *ValsPutRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ValsPutRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ValsPutRequest) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *ValsPutRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ValsPutRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ValsPutRequest) SetName(v string) {
	o.Name = v
}

func (o ValsPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValsPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ValsPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValsPutRequest := _ValsPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValsPutRequest)

	if err != nil {
		return err
	}

	*o = ValsPutRequest(varValsPutRequest)

	return err
}

type NullableValsPutRequest struct {
	value *ValsPutRequest
	isSet bool
}

func (v NullableValsPutRequest) Get() *ValsPutRequest {
	return v.value
}

func (v *NullableValsPutRequest) Set(val *ValsPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableValsPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableValsPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValsPutRequest(val *ValsPutRequest) *NullableValsPutRequest {
	return &NullableValsPutRequest{value: val, isSet: true}
}

func (v NullableValsPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValsPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


