/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectLinks{}

// ProjectLinks struct for ProjectLinks
type ProjectLinks struct {
	// The URL of this resource on this API
	Self string `json:"self"`
	// The URL of this resource on Val Town
	Html string `json:"html"`
}

type _ProjectLinks ProjectLinks

// NewProjectLinks instantiates a new ProjectLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectLinks(self string, html string) *ProjectLinks {
	this := ProjectLinks{}
	this.Self = self
	this.Html = html
	return &this
}

// NewProjectLinksWithDefaults instantiates a new ProjectLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectLinksWithDefaults() *ProjectLinks {
	this := ProjectLinks{}
	return &this
}

// GetSelf returns the Self field value
func (o *ProjectLinks) GetSelf() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *ProjectLinks) GetSelfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *ProjectLinks) SetSelf(v string) {
	o.Self = v
}

// GetHtml returns the Html field value
func (o *ProjectLinks) GetHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Html
}

// GetHtmlOk returns a tuple with the Html field value
// and a boolean to check if the value has been set.
func (o *ProjectLinks) GetHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Html, true
}

// SetHtml sets field value
func (o *ProjectLinks) SetHtml(v string) {
	o.Html = v
}

func (o ProjectLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["self"] = o.Self
	toSerialize["html"] = o.Html
	return toSerialize, nil
}

func (o *ProjectLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"self",
		"html",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectLinks := _ProjectLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectLinks)

	if err != nil {
		return err
	}

	*o = ProjectLinks(varProjectLinks)

	return err
}

type NullableProjectLinks struct {
	value *ProjectLinks
	isSet bool
}

func (v NullableProjectLinks) Get() *ProjectLinks {
	return v.value
}

func (v *NullableProjectLinks) Set(val *ProjectLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectLinks(val *ProjectLinks) *NullableProjectLinks {
	return &NullableProjectLinks{value: val, isSet: true}
}

func (v NullableProjectLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


