/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package valgo

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AliasVal200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AliasVal200Response{}

// AliasVal200Response A Val
type AliasVal200Response struct {
	// The name of this val
	Name string `json:"name"`
	// This val's id
	Id string `json:"id"`
	// The version of this val, starting at zero
	Version int32 `json:"version"`
	// TypeScript code associated with this val
	Code NullableString `json:"code"`
	// Whether this val is available publicly on Val Town
	Public bool `json:"public"`
	CreatedAt time.Time `json:"createdAt"`
	// This resource's privacy setting. Unlisted resources do not appear on profile pages or elsewhere, but you can link to them.
	Privacy string `json:"privacy"`
	// The type of a val. HTTP can receive web requests, Email can receive emails, Cron runs periodically, and Script can be used for libraries or one-off calculations
	Type string `json:"type"`
	// The URL of this resource on the Val Town website
	Url string `json:"url"`
	Links AliasVal200ResponseLinks `json:"links"`
	Author NullableAliasVal200ResponseAuthor `json:"author"`
	VersionCreatedAt *time.Time `json:"versionCreatedAt,omitempty"`
	// How many likes this val has received
	LikeCount int32 `json:"likeCount"`
	ReferenceCount int32 `json:"referenceCount"`
	// This val's readme, as Markdown
	Readme NullableString `json:"readme"`
}

type _AliasVal200Response AliasVal200Response

// NewAliasVal200Response instantiates a new AliasVal200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAliasVal200Response(name string, id string, version int32, code NullableString, public bool, createdAt time.Time, privacy string, type_ string, url string, links AliasVal200ResponseLinks, author NullableAliasVal200ResponseAuthor, likeCount int32, referenceCount int32, readme NullableString) *AliasVal200Response {
	this := AliasVal200Response{}
	this.Name = name
	this.Id = id
	this.Version = version
	this.Code = code
	this.Public = public
	this.CreatedAt = createdAt
	this.Privacy = privacy
	this.Type = type_
	this.Url = url
	this.Links = links
	this.Author = author
	this.LikeCount = likeCount
	this.ReferenceCount = referenceCount
	this.Readme = readme
	return &this
}

// NewAliasVal200ResponseWithDefaults instantiates a new AliasVal200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAliasVal200ResponseWithDefaults() *AliasVal200Response {
	this := AliasVal200Response{}
	return &this
}

// GetName returns the Name field value
func (o *AliasVal200Response) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AliasVal200Response) SetName(v string) {
	o.Name = v
}

// GetId returns the Id field value
func (o *AliasVal200Response) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AliasVal200Response) SetId(v string) {
	o.Id = v
}

// GetVersion returns the Version field value
func (o *AliasVal200Response) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *AliasVal200Response) SetVersion(v int32) {
	o.Version = v
}

// GetCode returns the Code field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AliasVal200Response) GetCode() string {
	if o == nil || o.Code.Get() == nil {
		var ret string
		return ret
	}

	return *o.Code.Get()
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AliasVal200Response) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Code.Get(), o.Code.IsSet()
}

// SetCode sets field value
func (o *AliasVal200Response) SetCode(v string) {
	o.Code.Set(&v)
}

// GetPublic returns the Public field value
func (o *AliasVal200Response) GetPublic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Public
}

// GetPublicOk returns a tuple with the Public field value
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Public, true
}

// SetPublic sets field value
func (o *AliasVal200Response) SetPublic(v bool) {
	o.Public = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AliasVal200Response) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AliasVal200Response) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetPrivacy returns the Privacy field value
func (o *AliasVal200Response) GetPrivacy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Privacy
}

// GetPrivacyOk returns a tuple with the Privacy field value
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetPrivacyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Privacy, true
}

// SetPrivacy sets field value
func (o *AliasVal200Response) SetPrivacy(v string) {
	o.Privacy = v
}

// GetType returns the Type field value
func (o *AliasVal200Response) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AliasVal200Response) SetType(v string) {
	o.Type = v
}

// GetUrl returns the Url field value
func (o *AliasVal200Response) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *AliasVal200Response) SetUrl(v string) {
	o.Url = v
}

// GetLinks returns the Links field value
func (o *AliasVal200Response) GetLinks() AliasVal200ResponseLinks {
	if o == nil {
		var ret AliasVal200ResponseLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetLinksOk() (*AliasVal200ResponseLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *AliasVal200Response) SetLinks(v AliasVal200ResponseLinks) {
	o.Links = v
}

// GetAuthor returns the Author field value
// If the value is explicit nil, the zero value for AliasVal200ResponseAuthor will be returned
func (o *AliasVal200Response) GetAuthor() AliasVal200ResponseAuthor {
	if o == nil || o.Author.Get() == nil {
		var ret AliasVal200ResponseAuthor
		return ret
	}

	return *o.Author.Get()
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AliasVal200Response) GetAuthorOk() (*AliasVal200ResponseAuthor, bool) {
	if o == nil {
		return nil, false
	}
	return o.Author.Get(), o.Author.IsSet()
}

// SetAuthor sets field value
func (o *AliasVal200Response) SetAuthor(v AliasVal200ResponseAuthor) {
	o.Author.Set(&v)
}

// GetVersionCreatedAt returns the VersionCreatedAt field value if set, zero value otherwise.
func (o *AliasVal200Response) GetVersionCreatedAt() time.Time {
	if o == nil || IsNil(o.VersionCreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.VersionCreatedAt
}

// GetVersionCreatedAtOk returns a tuple with the VersionCreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetVersionCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.VersionCreatedAt) {
		return nil, false
	}
	return o.VersionCreatedAt, true
}

// HasVersionCreatedAt returns a boolean if a field has been set.
func (o *AliasVal200Response) HasVersionCreatedAt() bool {
	if o != nil && !IsNil(o.VersionCreatedAt) {
		return true
	}

	return false
}

// SetVersionCreatedAt gets a reference to the given time.Time and assigns it to the VersionCreatedAt field.
func (o *AliasVal200Response) SetVersionCreatedAt(v time.Time) {
	o.VersionCreatedAt = &v
}

// GetLikeCount returns the LikeCount field value
func (o *AliasVal200Response) GetLikeCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LikeCount
}

// GetLikeCountOk returns a tuple with the LikeCount field value
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetLikeCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LikeCount, true
}

// SetLikeCount sets field value
func (o *AliasVal200Response) SetLikeCount(v int32) {
	o.LikeCount = v
}

// GetReferenceCount returns the ReferenceCount field value
func (o *AliasVal200Response) GetReferenceCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReferenceCount
}

// GetReferenceCountOk returns a tuple with the ReferenceCount field value
// and a boolean to check if the value has been set.
func (o *AliasVal200Response) GetReferenceCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceCount, true
}

// SetReferenceCount sets field value
func (o *AliasVal200Response) SetReferenceCount(v int32) {
	o.ReferenceCount = v
}

// GetReadme returns the Readme field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AliasVal200Response) GetReadme() string {
	if o == nil || o.Readme.Get() == nil {
		var ret string
		return ret
	}

	return *o.Readme.Get()
}

// GetReadmeOk returns a tuple with the Readme field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AliasVal200Response) GetReadmeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Readme.Get(), o.Readme.IsSet()
}

// SetReadme sets field value
func (o *AliasVal200Response) SetReadme(v string) {
	o.Readme.Set(&v)
}

func (o AliasVal200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AliasVal200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["id"] = o.Id
	toSerialize["version"] = o.Version
	toSerialize["code"] = o.Code.Get()
	toSerialize["public"] = o.Public
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["privacy"] = o.Privacy
	toSerialize["type"] = o.Type
	toSerialize["url"] = o.Url
	toSerialize["links"] = o.Links
	toSerialize["author"] = o.Author.Get()
	if !IsNil(o.VersionCreatedAt) {
		toSerialize["versionCreatedAt"] = o.VersionCreatedAt
	}
	toSerialize["likeCount"] = o.LikeCount
	toSerialize["referenceCount"] = o.ReferenceCount
	toSerialize["readme"] = o.Readme.Get()
	return toSerialize, nil
}

func (o *AliasVal200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"id",
		"version",
		"code",
		"public",
		"createdAt",
		"privacy",
		"type",
		"url",
		"links",
		"author",
		"likeCount",
		"referenceCount",
		"readme",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAliasVal200Response := _AliasVal200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAliasVal200Response)

	if err != nil {
		return err
	}

	*o = AliasVal200Response(varAliasVal200Response)

	return err
}

type NullableAliasVal200Response struct {
	value *AliasVal200Response
	isSet bool
}

func (v NullableAliasVal200Response) Get() *AliasVal200Response {
	return v.value
}

func (v *NullableAliasVal200Response) Set(val *AliasVal200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAliasVal200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAliasVal200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAliasVal200Response(val *AliasVal200Response) *NullableAliasVal200Response {
	return &NullableAliasVal200Response{value: val, isSet: true}
}

func (v NullableAliasVal200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAliasVal200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


