/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValsList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValsList200Response{}

// ValsList200Response A paginated result set
type ValsList200Response struct {
	Data []ValsList200ResponseDataInner `json:"data"`
	Links PaginationLinks `json:"links"`
}

type _ValsList200Response ValsList200Response

// NewValsList200Response instantiates a new ValsList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValsList200Response(data []ValsList200ResponseDataInner, links PaginationLinks) *ValsList200Response {
	this := ValsList200Response{}
	this.Data = data
	this.Links = links
	return &this
}

// NewValsList200ResponseWithDefaults instantiates a new ValsList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValsList200ResponseWithDefaults() *ValsList200Response {
	this := ValsList200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ValsList200Response) GetData() []ValsList200ResponseDataInner {
	if o == nil {
		var ret []ValsList200ResponseDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ValsList200Response) GetDataOk() ([]ValsList200ResponseDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ValsList200Response) SetData(v []ValsList200ResponseDataInner) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *ValsList200Response) GetLinks() PaginationLinks {
	if o == nil {
		var ret PaginationLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ValsList200Response) GetLinksOk() (*PaginationLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *ValsList200Response) SetLinks(v PaginationLinks) {
	o.Links = v
}

func (o ValsList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValsList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *ValsList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValsList200Response := _ValsList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValsList200Response)

	if err != nil {
		return err
	}

	*o = ValsList200Response(varValsList200Response)

	return err
}

type NullableValsList200Response struct {
	value *ValsList200Response
	isSet bool
}

func (v NullableValsList200Response) Get() *ValsList200Response {
	return v.value
}

func (v *NullableValsList200Response) Set(val *ValsList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableValsList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableValsList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValsList200Response(val *ValsList200Response) *NullableValsList200Response {
	return &NullableValsList200Response{value: val, isSet: true}
}

func (v NullableValsList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValsList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


