/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AliasVal200ResponseAuthor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AliasVal200ResponseAuthor{}

// AliasVal200ResponseAuthor The user who created this val
type AliasVal200ResponseAuthor struct {
	Id string `json:"id"`
	Username NullableString `json:"username"`
}

type _AliasVal200ResponseAuthor AliasVal200ResponseAuthor

// NewAliasVal200ResponseAuthor instantiates a new AliasVal200ResponseAuthor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAliasVal200ResponseAuthor(id string, username NullableString) *AliasVal200ResponseAuthor {
	this := AliasVal200ResponseAuthor{}
	this.Id = id
	this.Username = username
	return &this
}

// NewAliasVal200ResponseAuthorWithDefaults instantiates a new AliasVal200ResponseAuthor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAliasVal200ResponseAuthorWithDefaults() *AliasVal200ResponseAuthor {
	this := AliasVal200ResponseAuthor{}
	return &this
}

// GetId returns the Id field value
func (o *AliasVal200ResponseAuthor) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AliasVal200ResponseAuthor) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AliasVal200ResponseAuthor) SetId(v string) {
	o.Id = v
}

// GetUsername returns the Username field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AliasVal200ResponseAuthor) GetUsername() string {
	if o == nil || o.Username.Get() == nil {
		var ret string
		return ret
	}

	return *o.Username.Get()
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AliasVal200ResponseAuthor) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Username.Get(), o.Username.IsSet()
}

// SetUsername sets field value
func (o *AliasVal200ResponseAuthor) SetUsername(v string) {
	o.Username.Set(&v)
}

func (o AliasVal200ResponseAuthor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AliasVal200ResponseAuthor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["username"] = o.Username.Get()
	return toSerialize, nil
}

func (o *AliasVal200ResponseAuthor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAliasVal200ResponseAuthor := _AliasVal200ResponseAuthor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAliasVal200ResponseAuthor)

	if err != nil {
		return err
	}

	*o = AliasVal200ResponseAuthor(varAliasVal200ResponseAuthor)

	return err
}

type NullableAliasVal200ResponseAuthor struct {
	value *AliasVal200ResponseAuthor
	isSet bool
}

func (v NullableAliasVal200ResponseAuthor) Get() *AliasVal200ResponseAuthor {
	return v.value
}

func (v *NullableAliasVal200ResponseAuthor) Set(val *AliasVal200ResponseAuthor) {
	v.value = val
	v.isSet = true
}

func (v NullableAliasVal200ResponseAuthor) IsSet() bool {
	return v.isSet
}

func (v *NullableAliasVal200ResponseAuthor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAliasVal200ResponseAuthor(val *AliasVal200ResponseAuthor) *NullableAliasVal200ResponseAuthor {
	return &NullableAliasVal200ResponseAuthor{value: val, isSet: true}
}

func (v NullableAliasVal200ResponseAuthor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAliasVal200ResponseAuthor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


