/*
Val Town API

Val Town’s public API  OpenAPI JSON endpoint:  https://api.val.town/openapi.json

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MeGet200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeGet200ResponseLinks{}

// MeGet200ResponseLinks struct for MeGet200ResponseLinks
type MeGet200ResponseLinks struct {
	// URL of this user on this API
	Self string `json:"self"`
}

type _MeGet200ResponseLinks MeGet200ResponseLinks

// NewMeGet200ResponseLinks instantiates a new MeGet200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeGet200ResponseLinks(self string) *MeGet200ResponseLinks {
	this := MeGet200ResponseLinks{}
	this.Self = self
	return &this
}

// NewMeGet200ResponseLinksWithDefaults instantiates a new MeGet200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeGet200ResponseLinksWithDefaults() *MeGet200ResponseLinks {
	this := MeGet200ResponseLinks{}
	return &this
}

// GetSelf returns the Self field value
func (o *MeGet200ResponseLinks) GetSelf() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *MeGet200ResponseLinks) GetSelfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *MeGet200ResponseLinks) SetSelf(v string) {
	o.Self = v
}

func (o MeGet200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeGet200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["self"] = o.Self
	return toSerialize, nil
}

func (o *MeGet200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"self",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeGet200ResponseLinks := _MeGet200ResponseLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeGet200ResponseLinks)

	if err != nil {
		return err
	}

	*o = MeGet200ResponseLinks(varMeGet200ResponseLinks)

	return err
}

type NullableMeGet200ResponseLinks struct {
	value *MeGet200ResponseLinks
	isSet bool
}

func (v NullableMeGet200ResponseLinks) Get() *MeGet200ResponseLinks {
	return v.value
}

func (v *NullableMeGet200ResponseLinks) Set(val *MeGet200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableMeGet200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableMeGet200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeGet200ResponseLinks(val *MeGet200ResponseLinks) *NullableMeGet200ResponseLinks {
	return &NullableMeGet200ResponseLinks{value: val, isSet: true}
}

func (v NullableMeGet200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeGet200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


